num_epochs : 100
logging_freq : 100
seed : 1234
test : true
random_noise : true

dataloader:
  batch_size : 16384
  num_workers : 8
  train_shuffle : true
  test_shuffle : false

model:
  input_dim : 1024
  num_classes : 1000
  layers : 
    - 4096
    - 2048
  activation : "relu"
  norm_layer : "layer"

lr_scheduler_name : cosine

lr_scheduler:
  cosine :
    num_epochs : 20

dataset:
  root_dir : imagenet1k_clip_embeddings # change this to the dir where embeddings are stored
  debug : false

optim_name : adam

optim:
  adam :
    lr : 3e-4
    weight_decay : 1e-4
  sgd :
    lr : 1e-3
    momentum : 0.9
    weight_decay : 1e-4

wandb:
  project : clip_imagenet1k
  entity : sid1793
  mode : disabled # [online, offline, disabled]
  watch : false
  tags :
    - mlp_01
    - clip_embeddings

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
