num_epochs : 100
logging_freq : 100
seed : 1234
test : true
dataset_type : ffcv # pytorch or ffcv

dataloader:
  batch_size : 2048
  num_workers : 8
  train_shuffle : true
  test_shuffle : false

model:
  input_dim : 1024
  num_classes : 1000
  layers : 
    - 512
    - 512
  activation : "relu"
  batch_norm : false

lr_scheduler_name : cosine

lr_scheduler:
  cosine :
    num_epochs : 20

dataset:
  root_dir : /home/siddhesh1793/code/imagenet-clip-classifier/imagenet1k_clip_embeddings
  debug : false

optim_name : adam

optim:
  adam :
    lr : 1e-3
    weight_decay : 1e-4
  sgd :
    lr : 1e-3
    momentum : 0.9
    weight_decay : 1e-4

wandb:
  project : clip_imagenet1k
  entity : sid1793
  mode : online # [online, offline, disabled]
  watch : false
  tags :
    - mlp_01
    - clip_embeddings

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
