num_epochs : 100
logging_freq : 100
seed : 1234
test : true

dataset:
  root_dir : /home/siddhesh1793/code/imagenet-clip-classifier/imagenet1k_clip_embeddings
  batch_size : 2048
  num_workers : 8
  download : false
  type : pytorch # pytorch or fccv
  train_shuffle : true
  test_shuffle : false
  pin_memory : true
  debug : false

optim_name : adam

optim:
  adam :
    lr : 1e-3
    weight_decay : 1e-4
  sgd :
    lr : 1e-3
    momentum : 0.9
    weight_decay : 1e-4

wandb:
  project : clip_imagenet1k
  entity : sid1793
  mode : online # [online, offline, disabled]
  tags :
    - mlp_01
    - clip_embeddings

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
